## Documentation: http://docs.travis-ci.com/user/languages/julia/

language: julia

dist: xenial

os:
  - linux
  #- osx

notifications:
  email: false

git:
  depth: 99999999

jobs:
  include:
    - stage: TestPreviousRelease
      os: linux
    - stage: TestLatestRelease
      julia: 1.5
      os: linux
    - stage: TestNightly
      julia: nightly
      os: linux
    - stage: Documentation
      julia: nightly
      os: linux
      script:
       - julia --project=docs -e 'using Pkg; Pkg.develop(PackageSpec(url="https://github.com/StatisticalRethinkingJulia/StructuralCausalModels.jl"));Pkg.instantiate(); Pkg.develop(PackageSpec(path=pwd()))'
       - julia --project=docs --color=yes docs/make.jl
      after_success: skip

after_success:
  - julia --project=test/coverage -e 'using Pkg; Pkg.instantiate()'
  - julia --project=test/coverage test/coverage/coverage.jl
